version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Load environment variables from a .env file
    env_file: .env
    # Override the DATABASE_URL to use the service name 'db' as the hostname
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
    
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

# Declare the named volume to make it explicit
volumes:
  pgdata: