services:
  # FastAPI Web Service
  - type: web
    name: elibrary-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: fastapi run src/ --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JWT_ALGORITHM
        value: HS256
      - key: STORAGE_BACKEND
        value: local
      - key: JWT_SECRET
        generateValue: true
      - key: DOMAIN
        value: https://elibrary-api.onrender.com/api/v1
      # Email credentials - SET THESE IN RENDER DASHBOARD, NOT HERE!
      # - key: MAIL_USERNAME
      #   value: [SET IN RENDER DASHBOARD]
      # - key: MAIL_PASSWORD
      #   value: [SET IN RENDER DASHBOARD]
      - key: MAIL_FROM
        value: noreply@elibrary.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_SERVER
        value: smtp-relay.brevo.com
      - key: MAIL_FROM_NAME
        value: E-Library

  # PostgreSQL Database
  - type: pserv
    name: elibrary-postgres
    plan: free
    databaseName: elibrary
    databaseUser: elibrary_user

  # Redis for JWT blocklist
  - type: redis
    name: elibrary-redis
    plan: free
