"""Add cascade delete to downloads table

Revision ID: 4cc751b527ef
Revises: 593890ec6843
Create Date: 2025-07-22 08:03:22.026309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cc751b527ef'
down_revision: Union[str, Sequence[str], None] = '593890ec6843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('downloads_user_id_fkey'), 'downloads', type_='foreignkey')
    op.drop_constraint(op.f('downloads_book_id_fkey'), 'downloads', type_='foreignkey')
    op.create_foreign_key(None, 'downloads', 'books', ['book_id'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'downloads', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'downloads', type_='foreignkey')
    op.drop_constraint(None, 'downloads', type_='foreignkey')
    op.create_foreign_key(op.f('downloads_book_id_fkey'), 'downloads', 'books', ['book_id'], ['uid'])
    op.create_foreign_key(op.f('downloads_user_id_fkey'), 'downloads', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###
