"""Update Books Model

Revision ID: 593890ec6843
Revises: 52128adbe947
Create Date: 2025-07-16 16:58:27.190129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '593890ec6843'
down_revision: Union[str, Sequence[str], None] = '52128adbe947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('books', sa.Column('uploaded_by', sa.Uuid(), nullable=True))
    op.alter_column('books', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_foreign_key('fk_books_uploaded_by_users', 'books', 'users', ['uploaded_by'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_uploaded_by_users', 'books', type_='foreignkey')
    op.alter_column('books', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('books', 'uploaded_by')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
