"""Update models uid field

Revision ID: c021f2ae3e27
Revises: 1ee7ae09c8b0
Create Date: 2025-07-16 08:01:15.096368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c021f2ae3e27'
down_revision: Union[str, Sequence[str], None] = '1ee7ae09c8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'uid',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               postgresql_using="uid::uuid",
               existing_nullable=False)
    op.alter_column('users', 'uid',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               postgresql_using="uid::uuid",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('books', 'uid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
