"""Add downloads table

Revision ID: e24be4e6cbae
Revises: c021f2ae3e27
Create Date: 2025-07-16 08:45:33.464431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e24be4e6cbae'
down_revision: Union[str, Sequence[str], None] = 'c021f2ae3e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('was_emailed', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloads')
    # ### end Alembic commands ###
